<?php $this->extend('error/layout') ?>

<?php $this->section('content') ?>
	<div class="container">
		<div>
			<h1 class="page-title"><?= get_class($exception) ?></h1>
		</div>
		<div>
			<pre><?= $exception ?></pre>
		</div>
        
        <table class="table">
            <tr>
                <th>Arquivo</th>
                <td><?= $exception->getFile() ?></td>
            </tr>
            <tr>
                <th>Linha</th>
                <td><?= $exception->getLine() ?></td>
            </tr>
            <tr>
                <th></th>
                <td></td>
            </tr>
        </table>
        <pre>
        <?php foreach ($errorLines as $key => $value): ?><!--
            O pré é chato, tive que fazer essa gambi @Guilherme!
        --><div><?=$key?></div><!--
        --><?= htmlentities($value) ?><!--
        --><?php endforeach ?>
        </pre>
    </div>
<?php $this->endSection() ?>