<?php $this->extend('layout') ?>

<?php $this->section('content') ?>
<div ng-controller="infos">
    <h4 class='page-title'>Objetos no Maxters\Container</h4>
    <table class="table">
        <tr ng-repeat="(key, value) in infos">
            <th>{{ key }}</th>
            <td style="white-space: pre;">{{ value }}</td>
        </tr>
    </table>
</div>
<?php $this->endSection() ?>

<?php $this->section('scripts') ?>
<script type="text/javascript" src="/js/infos.js"></script>
<?php $this->endSection() ?>
